### PR TITLE
more than 3 chunks can uploaded resumUpload

### PR DESCRIPTION
**Pull request by sam-uraii**
before this commit only 2 chunks were able to be uploaded because of a bug which was resolved in this PR

### CODE REVIEW

**Comment by RobinBobin** [comment]
Please have a look at this piece from the official docs:

> Repeat steps 1 through 4 for each chunk that remains in the file. Use the Range header in the response to determine where to start the next chunk. Do not assume that the server received all bytes sent in the previous request.

**Comment by sam-uraii** [comment]
Okay agreed! with what you are saying that we will have to check the range for confirmation about the bytes transferred that.(sorry I missed that), **but I checked again, instead of workaround I found the problem-->** 
for example : 
totalBytes = 5000;
chunkSize = 1000;

After a success full API call for first chunk,  if the response code is 308 we call processRange(response);

```
now when response.headers.get('Range') is called it returns 
for first chunk -->        bytes=0-999
for second chunk-->   bytes=0-1999 INSTEAD of 1000-1999

so the code is perfect but what we are reading as range is not coming right..............
when  .reduce((previousValue, currentValue) => currentValue - previousValue + 1) is called it returns
for first chunk -->        999-0+1 = 1000
for second chunk-->   1999-0+1=2000 INSTEAD of 1999-1000 = 1000
           And then  this.__transferredByteCount += transferredByteCount gets executed so this.__transferredByteCount becomes 3000 instead of 2000


And then when we try to send third chunk, we are sending the chunk which is 2000-2999 BUT the 
from = this.__transferredByteCount = 3000
to = from + chunk.length - 1 = 3999 
'Content-Range', `bytes ${from}-${to}/${total}` = 'Content-Range', `bytes 3000-3999` INSTEAD of 2000-2999.
```
**ERROR comes:** 
[HttpError: Invalid request.  According to the Content-Range header, the upload offset is 3000 byte(s), which exceeds already uploaded size of 1999 byte(s).]

**Comment by sam-uraii** [comment]
yess sure.....

**Comment by sam-uraii** [comment]
Hi, my pr which I raised was wrong agreed..... but the doubt was right.....let me explain...--> 
When you use _processRange_  function you reduce the range's "currentVal - prevVal + 1" which is correct but the problem is that whenever you get a range in response you get 0-3999 (for the first chunk)and 0 - 7999 (for the second chunk) and 
 so on......your logic is right but response is not coming according to it........
 After calling  _processRange_ function you run --> 
**step 1** : const transferredByteCount = this.processRange(response);
**step2** : this.__transferredByteCount += transferredByteCount;

**now for the first chunck**  
step 1 gives you 4000.       [ response.range = 0-3999;     3999-0+1 = 4000;]
step 2 gives you 4000        [0 + 4000]


**_problem starts now_** 
**now for the second chunck**  
step 1 gives you 8000.       [ response.range = 0-7999;     7999-0+1 = 8000;]
_instead of 4000 [ response.range = 4000-7999;     7999-4000+1 = 4000;]_
step 2 gives you 12000        [ 4000 + 8000]
instead, it should have given us 8000    [4000+4000]


by applying the above solution we can take care of the range given in response and solve the problem as well but in my previous solution I was not taking care of range given in response.

**Comment by RobinBobin** [comment]
Hi!
Can you reproduce the issue in my [sample app](https://github.com/RobinBobin/gdrivetest)?
If so, could you share the file(s) you're trying to upload?

**Comment by sam-uraii** [comment]
So one video is of 20MB and other video is of 80MB. This is not letting me share this big of a video....you can take any video you want or I can also share the download link for them whatever you want. the Important part is that I am taking 4194304 bytes(4MB) as size of one chunk...

**Comment by RobinBobin** [comment]
Ok, got it.

Can you reproduce the issue in my [sample app](https://github.com/RobinBobin/gdrivetest)?

**Pull request closed without merging**
