### PR TITLE
Add files.update

### PR DESCRIPTION
**Pull request by nullmu0**
Example.
```
async moveFile(file_id, parent_id, oparent_id) {
        let data = await GDrive.files.update(file_id, {
            removeParents: oparent_id,
            addParents: parent_id,
            resource: {
                modifiedTime: new Date(Date.now()).toISOString(),
            },
        }).then(response => response.json())

        return data
}
```
resource is Request body
Same as google-api-nodejs-client

### CODE REVIEW

**Comment by RobinBobin** [comment]
Hello, Moon!

Thanks for the update. I'll gladly merge it. I'd like to kindly ask you to increase the version to 1.4.0 in `package.json` and add a couple of words to the readme. A link to the google api docs and an example will be great. And maybe the missing semicolons at the end of the lines in your code. I know it's nothing much, but that way it will look consistent with my code.

Thanks.

**Comment by nullmu0** [comment]
Is this right?

**Comment by nullmu0** [comment]
I newly added Delete Permission and About
```
        let data = await GDrive.about.get({
            fields: 'storageQuota'
        }).then(response => response.json())

        await GDrive.permissions.delete(file_id, permissionId)
```

**Comment by RobinBobin** [comment]
Yeah, that's great. Thanks. Merged.

**Comment by hjylewis** [comment]
@RobinBobin can this change be published?

**Comment by RobinBobin** [comment]
Done.

**Pull request merged**
