### PR TITLE
Fixed folder creation for use with appDataFolder space

### PR DESCRIPTION
**Pull request by Przytua**

### CODE REVIEW

**Comment by RobinBobin** [comment]
Hi!

Thanks for your contribution. I'll gladly merge, but one thing is unclear to me. Say, someone uses this library and they have

    const trashed = true;
    Files.getId(name, parents, mimeType, trashed);

and after they upgrade this will result in `spaces` being `true` and `trashed` being `false`, if I'm not mistaken. If you agree, would you just make `spaces` the last parameter?

Would you also increase the version to 1.5.0 and update the readme, please? The readme has a version section in the end. Adding a tiny summary to it will be great.

**Comment by RathiRohit** [comment]
Hi @Przytua, any updates on this? I was looking forward towards this PR for accessing appDataFolder from my app.

PS: If you are unavailable to work on this, I can raise another PR with these changes and improvements suggested to keep things moving :)

**Comment by cstehreem** [comment]
@Przytua I pulled these changes and tried to upload a file to appDataFolder. It seems to work when I upload file and gives me a 200 but doesn't allow me to download the file giving 404. The folder shows up empty if I try to list all files. Any idea what could be the reason?

**Comment by Przytua** [comment]
@RobinBobin sorry for late update. I've added the requested change.

@cstehreem to list items in the folder, I'm using:
```
    let result = await GDrive.files.list({
      q: `name contains '${folder}' and mimeType = '${MimeTypes.folder}' and 'appDataFolder' in parents`,
      spaces: 'appDataFolder',
      fields: 'files(id, name)',
    });
    if (!result.ok) {
      // handle error
    }
    const folders = await result.json();
    const folderId = folders.files[0]?.id;
    if (!folderId) {
      // handle error
    }
    result = await GDrive.files.list({
      q: `mimeType = '${MimeTypes.zip}' and '${folderId}' in parents`,
      spaces: 'appDataFolder',
      fields: 'files(id, name, modifiedTime)',
      orderBy: 'modifiedTime desc',
    });
    if (!result.ok) {
      // handle error
    }
    const files = await result.json();
```

But one thing that I noticed only on android is that when in query I used `=` instead of `contains` for folder name, it didn't find it. This caused a bug that created new folder everytime using `safeCreateFolder`. So another change that I did is I updated `Files.js` `getID` implementation to:
```
   async getId(name, parents, mimeType, spaces = 'drive', trashed = false) {
      const queryParams = {trashed};
      
      if (mimeType) {
         queryParams.mimeType = mimeType;
      }

      const paramsString = GDrive._stringifyQueryParams(queryParams, "", " and ", true)
      
      let result = await this.list({
         q: `name contains '${name}' and ${paramsString} and '${parents[0]}' in parents`,
         spaces: spaces,
      });
      
      if (!result.ok) {
         throw result;
      }
      
      const file = (await result.json()).files[0];
      
      return file ? file.id : file;
   }
```
and now it works properly for me.
I didn't add this change to this PR, as this may break some functionality (as it's not a strict check) but for my usecase it's ok. I did it locally using npm patch.

**Comment by RobinBobin** [comment]
@Przytua thanks. Now another line caught my eye. `Files.getId()`. You changed

    const queryParams = {name, trashed};

to

    const queryParams = {trashed};

How will I be able to search by name?

**Comment by RobinBobin** [comment]
I'm closing the PR, as
1) It's been inactive for a while.
2) I'm writing [v2](https://www.npmjs.com/package/@robinbobin/react-native-google-drive-api-wrapper) of this module and I'll deprecate this version soon.

If the functionality added with this PR is still needed, please open an issue.

**Pull request closed without merging**
